[package]
name = "aw"
description = "CLI tool to analyze websites for technologies used"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository = "https://github.com/gedex/site-analyzer"
homepage = "https://github.com/gedex/site-analyzer"
readme = "../../README.md"
keywords = ["web", "analyzer", "technology", "detection", "fingerprinting"]
categories = ["command-line-utilities", "web-programming"]

[[bin]]
name = "aw"
path = "src/main.rs"

[dependencies]
site-analyzer = { version = "0.1.0", path = "../analyzer" }
tokio.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

clap = { version = "4", features = ["derive", "color", "env"] }
colored = "2"
