use std::collections::HashMap;

use serde::Deserialize;
use serde_json::Value;

use crate::pattern::{parse_patterns_list, parse_string_list, KeyedPattern, Pattern};

// Raw JSON deserialization types (mirrors Wappalyzer schema exactly)

#[derive(Debug, Deserialize)]
pub struct RawTech {
    pub cats: Vec<u32>,

    #[serde(default)]
    pub website: Option<String>,

    #[serde(default)]
    pub description: Option<String>,

    #[serde(default)]
    pub cpe: Option<String>,

    #[serde(default)]
    pub icon: Option<String>,

    /// headers: { "Header-Name": "pattern" }
    #[serde(default)]
    pub headers: HashMap<String, Value>,

    /// html: "pattern" | ["p1","p2"]
    #[serde(default)]
    pub html: Option<Value>,

    /// scripts: "pattern" | ["p1","p2"]
    #[serde(default)]
    pub scripts: Option<Value>,

    /// meta: { "name": "pattern" }
    #[serde(default)]
    pub meta: HashMap<String, Value>,

    /// cookies: { "cookie-name": "pattern" }
    #[serde(default)]
    pub cookies: HashMap<String, Value>,

    /// js: { "global.property": "pattern" }
    #[serde(default)]
    pub js: HashMap<String, Value>,

    /// url: "pattern" | ["p1","p2"]
    #[serde(default)]
    pub url: Option<Value>,

    /// certIssuer: "string to match"
    #[serde(rename = "certIssuer", default)]
    pub cert_issuer: Option<String>,

    /// css: "pattern" | ["p1","p2"]
    #[serde(default)]
    pub css: Option<Value>,

    /// dns: { "ns": "pattern", "mx": "pattern", "txt": "pattern" }
    #[serde(default)]
    pub dns: HashMap<String, Value>,

    /// implies: "Tech" | ["Tech1","Tech2"] | "Tech\\;version:x"
    #[serde(default)]
    pub implies: Option<Value>,

    /// excludes: "Tech" | ["Tech1","Tech2"]
    #[serde(default)]
    pub excludes: Option<Value>,
}

#[derive(Debug, Deserialize)]
struct RawCategory {
    name: String,
}

#[derive(Debug, Deserialize)]
struct TechDatabase {
    technologies: HashMap<String, RawTech>,
    categories: HashMap<String, RawCategory>,
}

// Processed fingerprint — what the engine actually uses at runtime

#[derive(Debug, Clone)]
pub struct Fingerprint {
    pub name: String,
    pub cats: Vec<u32>,
    pub website: Option<String>,
    pub description: Option<String>,
    pub cpe: Option<String>,

    // Detection signals
    pub html_patterns: Vec<Pattern>,
    pub script_patterns: Vec<Pattern>,
    pub url_patterns: Vec<Pattern>,
    pub css_patterns: Vec<Pattern>,
    pub header_patterns: Vec<KeyedPattern>,
    pub meta_patterns: Vec<KeyedPattern>,
    pub cookie_patterns: Vec<KeyedPattern>,
    pub js_patterns: Vec<KeyedPattern>,
    pub cert_issuer: Option<String>,
    pub dns_patterns: Vec<KeyedPattern>,

    // Inference
    pub implies: Vec<ImpliedTech>,
    pub excludes: Vec<String>,
}

/// An implied technology, possibly with a version string from the implication
#[derive(Debug, Clone)]
pub struct ImpliedTech {
    /// Technology name (may include version suffix stripped already)
    pub name: String,
    /// Optional version override e.g. "5" when implies is "PHP\\;version:5"
    pub version: Option<String>,
}

/// Category metadata
#[derive(Debug, Clone)]
pub struct Category {
    pub id: u32,
    pub name: String,
}

/// The full loaded database
pub struct FingerprintDb {
    pub fingerprints: Vec<Fingerprint>,
    pub categories: HashMap<u32, Category>,
}

impl FingerprintDb {
    /// Load from the bundled technologies.json (embedded at compile time)
    /// Note: This file is generated by build.rs from individual technology files
    pub fn load() -> Self {
        let raw_json = include_str!("../../../generated/technologies.json");
        Self::from_json(raw_json)
    }

    pub fn from_json(json: &str) -> Self {
        let db: TechDatabase = serde_json::from_str(json)
            .expect("Failed to parse technologies.json — file may be corrupt");

        let categories: HashMap<u32, Category> = db
            .categories
            .iter()
            .filter_map(|(id_str, cat)| {
                id_str.parse::<u32>().ok().map(|id| {
                    (
                        id,
                        Category {
                            id,
                            name: cat.name.clone(),
                        },
                    )
                })
            })
            .collect();

        let fingerprints: Vec<Fingerprint> = db
            .technologies
            .into_iter()
            .map(|(name, raw)| build_fingerprint(name, raw))
            .collect();

        tracing::debug!(
            "Loaded {} fingerprints across {} categories",
            fingerprints.len(),
            categories.len()
        );

        FingerprintDb {
            fingerprints,
            categories,
        }
    }

    /// Look up a category name by numeric ID
    pub fn category_name(&self, id: u32) -> Option<&str> {
        self.categories.get(&id).map(|c| c.name.as_str())
    }
}

fn build_fingerprint(name: String, raw: RawTech) -> Fingerprint {
    // html patterns
    let html_patterns = raw
        .html
        .as_ref()
        .map(parse_patterns_list)
        .unwrap_or_default();

    // script patterns
    let script_patterns = raw
        .scripts
        .as_ref()
        .map(parse_patterns_list)
        .unwrap_or_default();

    // url patterns
    let url_patterns = raw
        .url
        .as_ref()
        .map(parse_patterns_list)
        .unwrap_or_default();

    // css patterns
    let css_patterns = raw
        .css
        .as_ref()
        .map(parse_patterns_list)
        .unwrap_or_default();

    // header patterns
    let header_patterns = build_keyed_patterns(&raw.headers);

    // meta patterns
    let meta_patterns = build_keyed_patterns(&raw.meta);

    // cookie patterns
    let cookie_patterns = build_keyed_patterns(&raw.cookies);

    // js patterns (checking for global variable presence)
    let js_patterns = build_keyed_patterns(&raw.js);

    // dns patterns
    let dns_patterns = build_keyed_patterns(&raw.dns);

    // implies
    let implies = raw
        .implies
        .as_ref()
        .map(|v| parse_string_list(v))
        .unwrap_or_default()
        .into_iter()
        .map(|s| parse_implied_tech(&s))
        .collect();

    // excludes
    let excludes = raw
        .excludes
        .as_ref()
        .map(|v| parse_string_list(v))
        .unwrap_or_default();

    Fingerprint {
        name,
        cats: raw.cats,
        website: raw.website,
        description: raw.description,
        cpe: raw.cpe,
        html_patterns,
        script_patterns,
        url_patterns,
        css_patterns,
        header_patterns,
        meta_patterns,
        cookie_patterns,
        js_patterns,
        cert_issuer: raw.cert_issuer,
        dns_patterns,
        implies,
        excludes,
    }
}

/// Build keyed patterns from a `HashMap<String, Value>` where value is
/// either a bare string pattern or an array of string patterns.
fn build_keyed_patterns(map: &HashMap<String, Value>) -> Vec<KeyedPattern> {
    let mut out = Vec::new();
    for (key, val) in map {
        let key_lower = key.to_lowercase();
        let patterns = parse_patterns_list(val);
        for pattern in patterns {
            out.push(KeyedPattern {
                key: key_lower.clone(),
                pattern,
            });
        }
    }
    out
}

/// Parse an implied tech string like "PHP\\;version:5" or just "MySQL"
fn parse_implied_tech(s: &str) -> ImpliedTech {
    let parts: Vec<&str> = s.split("\\;").collect();
    let name = parts[0].trim().to_string();
    let mut version: Option<String> = None;

    for tag in parts.iter().skip(1) {
        if let Some(v) = tag.strip_prefix("version:") {
            if !v.is_empty() {
                version = Some(v.to_string());
            }
        }
    }

    ImpliedTech { name, version }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_implied_tech_parsing() {
        let implied = parse_implied_tech("PHP\\;version:5");
        assert_eq!(implied.name, "PHP");
        assert_eq!(implied.version.as_deref(), Some("5"));

        let implied2 = parse_implied_tech("MySQL");
        assert_eq!(implied2.name, "MySQL");
        assert!(implied2.version.is_none());
    }
}
